export const skills = [
  "TypeScript",
  "UnityEngine- basic",
  "Articulate storyline",
  "Semantic & accessible HTML",
  "Responsive Web Design",
  "Markdown",
  "CSS BEM convention",
  "CSS Grid",
  "CSS Flexbox",
  "JavaScript ES6+",
  "Immutability",
  "React Router",
  "Redux-Saga",
  "Redux (Toolkit)",
  "React",
  "React Hooks",
  "Error handling",
  "Promises, Async/Await",
  "NPM",
  "Git",
  "Trello",
  "Teamwork",
  "Scrum",
  "Figma",
  "Working with API (fetch, axios)",
  "GitHub Pull Requests & Review",
];